# -*- coding: utf-8 -*-
from _helpers import page, capsule, sec, faq, svc, cs, post, src, ext, price, per
from _cityservice import cityservice_pages

SLUG = "belle-isle"

DRIVE_URL = "https://www.belleislefl.gov/sites/default/files/fileattachments/building_and_permitting/page/7581/241001_form_driveway_application_fillable.pdf"
ZONING_URL = "https://www.belleislefl.gov/building/page/zoning-permits"
WIKI_URL = "https://en.wikipedia.org/wiki/Belle_Isle,_Florida"
CR_POP_URL = "http://censusreporter.org/profiles/16000US1205300-belle-isle-fl/"
CR_YEAR_URL = "https://api.censusreporter.org/1.0/data/show/latest?table_ids=B25035&geo_ids=16000US1205300"

SRC = [
    ("City of Belle Isle, Driveway Review Application", DRIVE_URL),
    ("City of Belle Isle, Zoning Permits", ZONING_URL),
    ("Wikipedia, Belle Isle, Florida", WIKI_URL),
    ("Census Reporter, Belle Isle, FL", CR_POP_URL),
    ("Census Reporter API, Belle Isle median year structure built (B25035)", CR_YEAR_URL),
    "sjrwmd-watering", "dep-rule", "fs125572", "fs720-3045", "usgs-orange-gw",
]

# ---------------------------------------------------------------------- hub

HUB_BODY = "".join([
    sec("A city founded to keep a lake out of a drainage plan",
        f"<p>Belle Isle incorporated as a town on October 21, 1924, after residents organized specifically to stop Orange County from using Lake Conway's chain for drainage; the town went dormant in 1928 and reincorporated as a city in 1954, and today more than half of its land area is water "
        f"({ext(WIKI_URL, 'Wikipedia, Belle Isle, Florida')}). That history still shapes the permitting conversation: a {svc('concrete-patios', 'patio')}, dock or {svc('retaining-walls', 'retaining wall')} going in near the Conway Chain's shoreline is, more often than in most Orlando-area towns, a lakefront project first.</p>"),
    sec("A base allowance of 35 percent, calculated on the application itself",
        f"<p>Belle Isle's own Driveway Review Application walks a homeowner through the math directly: total lot area times 0.35 sets the allowable base impervious area, under City Code sections 50-74 through 50-77, before the house, driveway, walkway, pool, deck and accessory structures are added up against that figure "
        f"({ext(DRIVE_URL, 'City of Belle Isle, Driveway Review Application')}). The same application sets the outer edge of a front-yard driveway no closer than 3 feet to the property line, and requires a pre-inspection, approved by city staff, before the concrete pour itself.</p>"),
    sec("Pavers beyond the driveway apron need a separate agreement with the city",
        f"<p>Belle Isle's driveway form draws a specific line: pavers used on the driveway apron itself are covered by that application, but \"pavers beyond the scope of the driveway area must be filed with UES under a Building Permit,\" UES being the engineering firm the city contracts to run its permitting "
        f"({ext(DRIVE_URL, 'City of Belle Isle, Driveway Review Application')}). A {svc('paver-driveways', 'paver driveway')} that extends into a wider paver walkway or courtyard crosses that line and needs the separate building-permit review rather than riding along on the driveway form.</p>"),
    sec("A smaller, older city than most of its Orange County neighbors",
        f"<p>Belle Isle's American Community Survey estimate counts 7,444 residents, the smallest population among the Orange County towns covered on this site, with a median year of home construction of 1977, older than Winter Park's 1976 figure is young and on par with it "
        f"({ext(CR_POP_URL, 'Census Reporter, Belle Isle, FL')}; {ext(CR_YEAR_URL, 'Census Reporter API, B25035')}). Lake Conway Estates, one of the city's original subdivisions, started construction around 1960, which puts a real share of Belle Isle's driveways and patios well past the point where {svc('concrete-repair', 'resurfacing')} is the expected next step rather than a sign of trouble.</p>"),
    sec("Stormwater has to stay on the lot, not run toward the chain",
        f"<p>The driveway application requires the homeowner to show the direction of drainage with arrows on the submitted plan and certifies that all stormwater generated by the new driveway \"shall be retained on site\" without adding runoff onto neighboring property "
        f"({ext(DRIVE_URL, 'City of Belle Isle, Driveway Review Application')}). On a city where the Conway Chain's water quality is the reason the town exists in the first place, that on-site retention rule reads less like boilerplate and more like the point.</p>"),
    "<!--AUTO:city-services-->",
])

HUB_FAQS = [
    faq("What code section governs impervious coverage in Belle Isle?",
        f"City Code sections 50-74 through 50-77, which the city's own driveway application uses to calculate a base allowable impervious area equal to 35 percent of the total lot "
        f"({ext(DRIVE_URL, 'City of Belle Isle, Driveway Review Application')})."),
    faq("How close to the property line can a Belle Isle driveway sit?",
        "The city's driveway regulations set the outer edge of a front-yard driveway no closer than 3 feet from the property line, and any curb break or alteration needs city approval first."),
    faq("Do pavers outside the driveway footprint need a different permit in Belle Isle?",
        "Yes. Pavers on the driveway apron itself go through the driveway application, but pavers used anywhere beyond that footprint, a patio or walkway, for example, have to be filed as a separate building permit through UES, the city's contracted permitting engineer."),
    faq("Why does Belle Isle exist as its own city rather than part of Orange County?",
        "Belle Isle incorporated in 1924 specifically so residents could stop Orange County from using the Lake Conway chain for drainage, and the city still sits more than half covered in water today."),
    faq("How old is the typical home in Belle Isle?",
        "The city's median year of construction is 1977, and one of its original subdivisions, Lake Conway Estates, started building around 1960, so a meaningful share of the city's original flatwork is now well past the half-century mark."),
    faq("What should a Belle Isle homeowner confirm before hiring a contractor?",
        f"Have the contractor run the 35 percent base impervious math against your actual lot size rather than an estimate, pin down in writing whether the job needs the driveway form or the separate UES building permit for pavers beyond the apron, and verify the business on the state's license lookup. "
        f"{post('how-to-choose-a-concrete-contractor-orlando', 'This breakdown of choosing a concrete contractor')} fills in the rest."),
]

HUB = page("/belle-isle-fl/", "city", "Concrete, Pavers & Turf Contractor in Belle Isle, FL",
           "Concrete, pavers and turf in Belle Isle, FL: the city's 35% base coverage math, the 3-foot driveway setback, and Lake Conway's shoreline, October 2026.",
           "Concrete, Pavers and Artificial Turf for Belle Isle Homes",
           capsule(f"Opera pours concrete and lays pavers and artificial turf for Belle Isle, an Orange County city of 7,444 residents built around the Lake Conway chain, more than half the city's land area water. "
                   f"A concrete driveway here runs {price('concrete-driveway')} per {per('concrete-driveway')} this October, measured against the city's own 35 percent base impervious allowance."),
           HUB_BODY, faqs=HUB_FAQS, sources=SRC, city=SLUG,
           crumbs=[("Service areas", "/service-areas/"), ("Orlando & Central Florida", "/central-florida/")], crumb="Belle Isle",
           related=[("/central-florida/", "The Orlando-unit coverage page"),
                    ("/orlando-fl/", "Concrete, pavers and turf in Orlando"),
                    ("/winter-park-fl/", "Concrete, pavers and turf in Winter Park"),
                    ("/blog/orange-county-orlando-driveway-patio-permits/", "Orlando and Orange County permits"),
                    ("/compare/concrete-vs-pavers/", "Concrete vs. pavers")],
           eyebrow="Concrete · Pavers · Turf in Belle Isle, FL")

# ---------------------------------------------------------------------- services

LOCAL = {}

# 1. concrete-driveways -------------------------------------------------------
LOCAL["concrete-driveways"] = {
    "title": "Concrete Driveways in Belle Isle, FL – Permits",
    "meta": "Concrete driveway installers in Belle Isle, FL: the city's 35% base coverage math, a 3-foot setback, and the on-site stormwater rule, October 2026.",
    "h1": "Pouring a Concrete Driveway in Belle Isle",
    "lede": capsule(f"Expect the {price('concrete-driveway')} per {per('concrete-driveway')} statewide market range to apply to a Belle Isle concrete driveway this October. "
                     "The city's own Driveway Review Application sets a base allowance of 35 percent of the lot for impervious coverage, and the permit requires a pre-inspection before the crew's first truck of concrete even arrives."),
    "sections": [
        ("Thirty-five percent of the lot, calculated right on the application",
         f"<p>Belle Isle's driveway form has the homeowner multiply total lot area by 0.35 to get the allowable base impervious area under code sections 50-74 through 50-77, then add up the house, driveway, walkway and any accessory structures against that number "
         f"({ext(DRIVE_URL, 'City of Belle Isle, Driveway Review Application')}). A driveway that pushes the running total past that 35 percent base sometimes still works, but it moves the application into a more involved review rather than a routine sign-off.</p>"),
        ("A pre-inspection before the pour, not just an inspection after",
         f"<p>Unlike a permit that only checks the finished work, Belle Isle requires the pre-inspection to be reviewed and approved by city staff before the application itself is approved, and a separate inspection has to be completed prior to the actual concrete pour "
         f"({ext(DRIVE_URL, 'City of Belle Isle, Driveway Review Application')}). The driveway's outer edge also can't sit closer than 3 feet to the property line in the front yard, and any curb break needs sign-off from the Building Official first.</p>"),
    ],
    "scenario": ("Replacing a driveway on a Lake Conway Estates lot, worked out in square feet",
                 f"<p>Take a Belle Isle home in one of the subdivisions that started building around 1960, where the original 10 by 20 foot driveway, 200 square feet, has cracked at the edges after six decades. At {price('concrete-driveway')} per {per('concrete-driveway')}, a straight repour runs roughly $1,200 to $3,000 before the permit, and because the lot sits close to Lake Conway, the stormwater-direction arrows on the submitted plan matter more here than on a landlocked street further from the chain.</p>"),
    "faqs": [
        faq("How is Belle Isle's driveway coverage limit calculated?",
            "The city's own application multiplies total lot area by 0.35 to set the base allowable impervious area under code sections 50-74 through 50-77, before the house, driveway and other hard surfaces are totaled against it."),
        faq("Does Belle Isle inspect a driveway before the concrete is poured?",
            "Yes. A pre-inspection has to be reviewed and approved by city staff before the application itself is approved, in addition to the inspection required before the actual pour."),
        faq("How close to the property line can a Belle Isle driveway be built?",
            "The outer edge of a front-yard driveway can't sit closer than 3 feet from the property line, and any curb break needs separate approval from the Building Official."),
    ],
    "sources": SRC,
}

# 2. paver-patios --------------------------------------------------------------
LOCAL["paver-patios"] = {
    "title": "Paver Patios & Walkways in Belle Isle, FL",
    "meta": "Paver patio installers in Belle Isle, FL: why a patio needs a separate building permit from the driveway form, near the Lake Conway chain, October 2026.",
    "h1": "Paver Patios and Walkways for a Belle Isle Home",
    "lede": capsule(f"A paver patio or walkway in Belle Isle runs {price('paver-patio')} per {per('paver-patio')} as of October 2026. "
                     "Unlike pavers laid on the driveway apron, a patio or walkway beyond that footprint goes through a separate building permit with the city's contracted engineering firm rather than the driveway application."),
    "sections": [
        ("Beyond the apron, the paperwork changes",
         f"<p>Belle Isle's driveway form is specific about where its own coverage ends: pavers on the apron are reviewed with the driveway application, but anything beyond that scope, a patio, a side-yard walkway, has to be filed as its own building permit through UES, the firm the city contracts to administer permitting "
         f"({ext(DRIVE_URL, 'City of Belle Isle, Driveway Review Application')}). That's a different office path than the driveway review, even though both ultimately answer to the same 35 percent base impervious calculation.</p>"),
        ("The same 35 percent math still applies once the patio is added in",
         f"<p>A {svc('paver-patios', 'paver patio')} still counts toward the base impervious allowance set by multiplying total lot area by 0.35 under code sections 50-74 through 50-77 "
         f"({ext(DRIVE_URL, 'City of Belle Isle, Driveway Review Application')}). On a lot that already fronts the chain, pushing a patio closer to the bank narrows the margin against both that 35 percent figure and the state's own setback for anything installed near open water, which is why we walk the shoreline distance on site rather than scaling it off a plat.</p>"),
    ],
    "scenario": ("A lakeside patio addition near Lake Conway, worked out in square feet",
                 f"<p>Picture a Belle Isle home on the Conway Chain adding a 16 by 14 foot paver patio, 224 square feet, between the house and the shoreline. At {price('paver-patio')} per {per('paver-patio')}, that patio runs roughly $2,240 to $3,584, filed as its own building permit through UES rather than riding along on a driveway application, and checked against the lot's 35 percent base coverage figure before the final footprint is set.</p>"),
    "faqs": [
        faq("Does a Belle Isle patio use the same permit as the driveway?",
            "No. Pavers on the driveway apron itself are covered by the driveway application, but a patio or walkway beyond that footprint needs its own building permit filed through UES, the city's contracted engineering firm."),
        faq("Does a patio count toward Belle Isle's 35 percent base coverage figure?",
            "Yes. The same lot-area-times-0.35 calculation that sets the driveway's allowance also includes the patio, walkway and any accessory structures on the property."),
        faq("Are there extra rules for a patio near the Lake Conway shoreline?",
            "The 35 percent base-coverage figure doesn't change for a waterfront lot, but a design that stretches a patio right up to the bank is worth running past the state's setback rules for water-adjacent turf and plantings before the final drawing is cut."),
    ],
    "sources": SRC,
}

# 3. artificial-turf -------------------------------------------------------------
LOCAL["artificial-turf"] = {
    "title": "Artificial Turf in Belle Isle, FL – Water Setbacks",
    "meta": "Artificial turf installers in Belle Isle, FL: the state's 10-foot lake setback, critical on a city that's more than half water, October 2026.",
    "h1": "Artificial Turf for Belle Isle Yards",
    "lede": capsule(f"Artificial turf in Belle Isle falls in the {price('artificial-turf')} {per('artificial-turf')} range as of October 2026. "
                     "Most of the city's oldest lots along the Conway Chain were seawalled decades ago for boat access, which in practice is also what decides whether the state's new water-body setback for turf ends up mattering on a given property."),
    "sections": [
        ("Seawalls are common here, and they change the math",
         f"<p>Rule 62-308.100 builds in an exception that matters more in Belle Isle than almost anywhere else Opera works: the usual requirement to keep new turf 10 feet from a pond, canal or lake disappears wherever a seawall already separates the yard from the water "
         f"({src('dep-rule', 'Florida Administrative Code, Rule 62-308.100')}). Because so much of the Conway Chain's original shoreline was bulkheaded for docks and boat lifts decades ago "
         f"({ext(WIKI_URL, 'Wikipedia, Belle Isle, Florida')}), a fair number of Belle Isle turf jobs skip the setback question entirely once the seawall is confirmed on site.</p>"),
        ("On an open bank, the rest of the state spec still applies in full",
         f"<p>Where a lot doesn't have a seawall, or the turf runs along a different edge of the property than the bulkhead covers, the rule's other pieces take over: a washed base rather than ordinary fill, natural infill instead of crumb rubber, and no irrigation line buried under the turf itself "
         f"({src('dep-rule', 'Florida Administrative Code, Rule 62-308.100')}). F.S. 125.572 sets a ceiling on how far any local rule can go beyond that statewide spec "
         f"({src('fs125572', 'F.S. 125.572')}).</p>"),
    ],
    "scenario": ("Turf on a seawalled Conway Chain lot, worked out in square feet",
                 f"<p>Take a Belle Isle backyard with an existing concrete seawall between the pool cage and the chain, where 400 square feet of lawn between the cage and the bulkhead has gone patchy under salt spray and boat traffic. At {price('artificial-turf')} per {per('artificial-turf')}, turfing that strip runs roughly $4,000 to $7,200, and because the seawall already separates the yard from open water, the installer can run the turf right up to the bulkhead without measuring off the usual 10-foot buffer.</p>"),
    "faqs": [
        faq("Does a Belle Isle lot need a seawall survey before a turf quote?",
            "Checking for an existing seawall is one of the first steps, since its presence determines whether the state's 10-foot water setback applies to that stretch of yard at all."),
        faq("What if part of a Belle Isle lot is seawalled and part isn't?",
            "The setback question is answered edge by edge: a seawalled section lets turf run to the bulkhead, while an open bank elsewhere on the same property still needs the full 10-foot buffer."),
        faq("Does an HOA on the Conway Chain get a say over turf placement?",
            "Only within the limits state law sets; an association can't go further than F.S. 125.572 already allows once an install meets the state's construction standard."),
    ],
    "sources": SRC,
}


def get_pages():
    return [HUB] + cityservice_pages(SLUG, LOCAL)
